### PR TITLE
feature/rebase-getCurrentState

### PR DESCRIPTION
**Pull request by rider-griffin**
- Fixes merge conflicts with app.js in order to get save features merged

### CODE REVIEW

**Review by otacke — CHANGES_REQUESTED** [review]
Hi, thanks! I can't keep up with all my open pull-requests (https://github.com/otacke/h5p-todo#open-pull-requests-for-bugfixes-and-new-features-for-existing-content-types). Much obliged. But before I take a 2nd look: Could you please stick with the H5P project convention and use single quotes?

**Comment by rider-griffin** [comment]
> Hi, thanks! I can't keep up with all my open pull-requests (https://github.com/otacke/h5p-todo#open-pull-requests-for-bugfixes-and-new-features-for-existing-content-types). Much obliged. But before I take a 2nd look: Could you please stick with the H5P project convention and use single quotes?

Thanks for getting back to me, looks like you have a lot on your plate. I went ahead and followed h5p convention and applied single quotes.

**Comment by otacke** [comment]
@rider-griffin I am sorry again: Have you potentially been automatically changing the formatting of the code? 

Removing obsolete spaces inside parantheses, for instance, is fine although those things should be done in a separate commit. Indenting arrow functions differently is rather a matter of taste (but also should have been done in a separate "Change formatting" commit). The thing that's definitely not good: The H5P coding guide (https://h5p.org/documentation/for-developers/coding-guidelines) requires `else` to be put on a separate line not on the same line as the closing `}` of the `if`.

I'd expect your pull request to just cover the conflicts that are currently mentioned in https://github.com/h5p/h5p-interactive-book/pull/59 (but look at all the lines your request wants to change).

**Comment by otacke** [comment]
@rider-griffin That feature has been merged into the official repository already. Please add stuff there if you think that something is missing or wrong.

**Pull request closed without merging**
